services:
# --- Frontend Service ---
  minidocs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - recker-net
    restart: unless-stopped
    depends_on:
      minidocs-backend:
        condition: service_started
    expose:
      - "5173"

  # --- Backend API ---
  minidocs-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    networks:
      - recker-net
    restart: always
    expose:
      - "8000"




networks:
  recker-net:
    external: true


